import React, { useState, useEffect, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  Dimensions,
  Animated,
  StatusBar,
  Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ChevronLeft, Filter, Download, ArrowUpCircle, ArrowDownCircle, TrendingUp, FileText } from 'lucide-react-native';
import { LinearGradient } from 'expo-linear-gradient';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { getTransactions } from '../database/db';
import { theme } from '../theme';
import GlassCard from './GlassCard';

const { width } = Dimensions.get('window');

export default function Report({ user, onBack }) {
  const [data, setData] = useState([]);
  const [activeTab, setActiveTab] = useState('all'); // all, income, expense

  const fadeAnim = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    const fetchTransactions = async () => {
      if (!user || !user.id) return;
      try {
        const transactions = await getTransactions(user.id);
        setData(transactions);
        Animated.timing(fadeAnim, {
          toValue: 1,
          duration: 800,
          useNativeDriver: true,
        }).start();
      } catch (error) {
        console.error('Error fetching transactions in Report:', error);
      }
    };
    fetchTransactions();
  }, [user]);

  const filteredData = data.filter(t => {
    if (activeTab === 'all') return true;
    return t.type === activeTab;
  });

  const totals = filteredData.reduce((acc, t) => acc + t.amount, 0);

  const handleExport = async () => {
    try {
      const htmlContent = `
        <html>
          <head>
            <style>
              body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #1e293b; background: #fff; }
              .header { border-bottom: 2px solid #6366f1; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }
              .title { font-size: 28px; font-weight: bold; color: #6366f1; }
              .summary { background: #f8fafc; padding: 20px; border-radius: 12px; margin-bottom: 30px; border: 1px solid #e2e8f0; }
              .summary-item { font-size: 16px; margin: 5px 0; }
              .totals { font-size: 24px; font-weight: 800; color: #1e293b; margin-top: 10px; }
              table { width: 100%; border-collapse: collapse; margin-top: 20px; }
              th { text-align: left; padding: 12px; background: #6366f1; color: #fff; font-weight: bold; }
              td { padding: 12px; border-bottom: 1px solid #e2e8f0; font-size: 14px; }
              .income { color: #10b981; font-weight: bold; }
              .expense { color: #f43f5e; font-weight: bold; }
              .footer { margin-top: 50px; font-size: 12px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 20px; }
            </style>
          </head>
          <body>
            <div class="header">
              <div class="title">Premium Expense Report</div>
              <div style="text-align: right">
                <small>${new Date().toLocaleDateString()}</small><br/>
                <strong>User: ${user?.name || 'Valued User'}</strong>
              </div>
            </div>
            
            <div class="summary">
              <div class="summary-item">Report Type: <strong>${activeTab.toUpperCase()}</strong></div>
              <div class="summary-item">Transaction Count: <strong>${filteredData.length}</strong></div>
              <div class="totals">Total Amount: Rs ${totals.toLocaleString()}</div>
            </div>

            <table>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Category</th>
                  <th>Type</th>
                  <th>Amount</th>
                </tr>
              </thead>
              <tbody>
                ${filteredData.map(t => `
                  <tr>
                    <td>${t.date}</td>
                    <td>${t.category}</td>
                    <td>${t.type === 'income' ? 'Income' : 'Expense'}</td>
                    <td class="${t.type}">Rs ${t.amount.toLocaleString()}</td>
                  </tr>
                `).join('')}
              </tbody>
            </table>

            <div class="footer">
              Generated by Premium Expense Tracker 💎<br/>
              Locally stored and secured platform.
            </div>
          </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html: htmlContent });
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: 'Download Expense Report',
        UTI: 'com.adobe.pdf',
      });
    } catch (error) {
      console.error('Export Error:', error);
      Alert.alert('Export Failed', 'An error occurred while generating your report.');
    }
  };

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="light-content" />
      <LinearGradient
        colors={[theme.colors.background, '#1e293b']}
        style={styles.background}
      />

      <View style={styles.header}>
        <TouchableOpacity onPress={onBack} style={styles.backButton}>
          <ChevronLeft size={28} color={theme.colors.text} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Analytics</Text>
        <TouchableOpacity style={styles.filterButton}>
          <Filter size={22} color={theme.colors.text} />
        </TouchableOpacity>
      </View>

      <Animated.ScrollView
        style={[styles.scrollContent, { opacity: fadeAnim }]}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.tabContainer}>
          {['all', 'income', 'expense'].map((tab) => (
            <TouchableOpacity
              key={tab}
              style={[styles.tab, activeTab === tab && styles.activeTab]}
              onPress={() => setActiveTab(tab)}
            >
              <Text style={[
                styles.tabText,
                activeTab === tab && styles.activeTabText
              ]}>
                {tab.charAt(0).toUpperCase() + tab.slice(1)}
              </Text>
            </TouchableOpacity>
          ))}
        </View>

        <GlassCard style={styles.summaryCard}>
          <Text style={styles.summaryLabel}>Total {activeTab === 'all' ? 'Transactions' : activeTab}</Text>
          <Text
            style={[
              styles.summaryAmount,
              activeTab === 'expense' && { color: theme.colors.expense },
              activeTab === 'income' && { color: theme.colors.income }
            ]}
            numberOfLines={1}
            adjustsFontSizeToFit
          >
            Rs {totals.toLocaleString()}
          </Text>
          <View style={styles.summaryFooter}>
            <TrendingUp size={16} color={theme.colors.success} style={{ marginRight: 6 }} />
            <Text style={styles.summaryTrend}>+12.5% from last month</Text>
          </View>
        </GlassCard>

        <View style={styles.transactionsHeader}>
          <Text style={styles.transactionsTitle}>Details</Text>
          <TouchableOpacity>
            <Download size={20} color={theme.colors.primaryLight} />
          </TouchableOpacity>
        </View>

        <View style={styles.list}>
          {filteredData.length === 0 ? (
            <View style={styles.emptyState}>
              <Text style={styles.emptyStateText}>No history found</Text>
            </View>
          ) : (
            filteredData.map((t) => (
              <GlassCard key={t.id} style={styles.item}>
                <View style={styles.itemMain}>
                  <View style={[
                    styles.iconWrapper,
                    { backgroundColor: t.type === 'income' ? 'rgba(16, 185, 129, 0.1)' : 'rgba(244, 63, 94, 0.1)' }
                  ]}>
                    {t.type === 'income' ? (
                      <ArrowUpCircle size={22} color={theme.colors.income} />
                    ) : (
                      <ArrowDownCircle size={22} color={theme.colors.expense} />
                    )}
                  </View>
                  <View style={{ flex: 1, paddingRight: 8 }}>
                    <Text style={styles.itemCategory} numberOfLines={1}>{t.category}</Text>
                    <Text style={styles.itemDate}>{t.date} • {t.time}</Text>
                  </View>
                </View>
                <View style={styles.itemRight}>
                  <Text
                    style={[
                      styles.itemAmount,
                      { color: t.type === 'income' ? theme.colors.income : theme.colors.expense }
                    ]}
                    numberOfLines={1}
                    adjustsFontSizeToFit
                  >
                    {t.type === 'income' ? '+' : '-'}Rs {t.amount.toLocaleString()}
                  </Text>
                  {t.description ? <Text style={styles.itemDesc}>{t.description}</Text> : null}
                </View>
              </GlassCard>
            ))
          )}
        </View>
        <View style={{ height: 100 }} />
      </Animated.ScrollView>

      <TouchableOpacity
        style={styles.exportButton}
        onPress={handleExport}
      >
        <LinearGradient
          colors={[theme.colors.primary, theme.colors.accent]}
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 0 }}
          style={styles.exportGradient}
        >
          <FileText size={20} color="#fff" style={{ marginRight: 8 }} />
          <Text style={styles.exportText}>Generate & Download PDF</Text>
        </LinearGradient>
      </TouchableOpacity>
    </SafeAreaView>
  );
}

// Add TrendingUp as it was missing from lucide-react-native imports in previous context but let's assume it's available


const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.md,
  },
  headerTitle: {
    ...theme.typography.h3,
    color: theme.colors.text,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.05)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.05)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollContent: {
    flex: 1,
  },
  tabContainer: {
    flexDirection: 'row',
    paddingHorizontal: theme.spacing.xl,
    marginVertical: theme.spacing.lg,
  },
  tab: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 20,
    marginRight: 10,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  activeTab: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  tabText: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.textLight,
  },
  activeTabText: {
    color: '#fff',
  },
  summaryCard: {
    marginHorizontal: theme.spacing.xl,
    padding: theme.spacing.xl,
    alignItems: 'center',
    marginBottom: theme.spacing.xl,
  },
  summaryLabel: {
    ...theme.typography.caption,
    color: theme.colors.textLight,
    marginBottom: 8,
  },
  summaryAmount: {
    fontSize: 34,
    fontWeight: '900',
    color: theme.colors.text,
    marginBottom: 8,
  },
  summaryFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(74, 222, 128, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  summaryTrend: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.colors.success,
  },
  transactionsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.xl,
    marginBottom: theme.spacing.md,
  },
  transactionsTitle: {
    ...theme.typography.h3,
    color: theme.colors.text,
  },
  list: {
    paddingHorizontal: theme.spacing.xl,
  },
  item: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: theme.spacing.md,
    paddingHorizontal: theme.spacing.md,
    marginBottom: 10,
    minHeight: 75,
  },
  itemMain: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  iconWrapper: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  itemCategory: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.text,
  },
  itemDate: {
    fontSize: 12,
    color: theme.colors.textLight,
    marginTop: 2,
  },
  itemRight: {
    alignItems: 'flex-end',
    minWidth: 90,
    marginLeft: 10,
  },
  itemAmount: {
    fontSize: 15,
    fontWeight: '800',
  },
  itemDesc: {
    fontSize: 11,
    color: theme.colors.textLight,
    marginTop: 2,
    maxWidth: 120,
    textAlign: 'right',
  },
  emptyState: {
    alignItems: 'center',
    marginTop: 50,
  },
  emptyStateText: {
    color: theme.colors.textLight,
    fontSize: 16,
    fontWeight: '500',
  },
  exportButton: {
    position: 'absolute',
    bottom: 30,
    left: theme.spacing.xl,
    right: theme.spacing.xl,
    height: 60,
    borderRadius: 20,
    overflow: 'hidden',
    ...theme.shadows.lg,
  },
  exportGradient: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  exportText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  }
});